import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className="bg-gray-300">
			<body>
				<header>
					<h1 className="text-3xl font-bold uppercase text-blue-900">F1Stats</h1>
				</header>
				<nav>
					<ul className="flex gap-4 font-bold">
						<li>
							<Link href="/circuits">Circuits</Link>
						</li>
						<li>
							<Link href="/drivers">Drivers</Link>
						</li>
						<li>
							<Link href="/constructors">Constructors</Link>
						</li>
						<li>
							<Link href="/seasons">Seasons</Link>
						</li>
					</ul>
				</nav>
				<main>{children}</main>
				<footer>
					<span>
						Data provided by the{" "}
						<a href="http://ergast.com/mrd/" target="_blank">
							Ergast API
						</a>
					</span>
				</footer>
			</body>
		</html>
	);
}
